// This file was auto-generated by prisma-generator-typescript-interfaces

export interface admins {
  id: bigint;
  first_name: string | null;
  last_name: string | null;
  gender: string | null;
  email: string | null;
  mobile_number: string;
  password: string | null;
  birthdate: Date | null;
  ssn: string | null;
  otp_secret: string | null;
  status: number;
  is_verified: boolean;
  deleted_at: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
  provider_agents?: provider_agents[];
}

export interface cache {
  key: string;
  value: string;
  expiration: number;
}

export interface cache_locks {
  key: string;
  owner: string;
  expiration: number;
}

export interface customer_subscriptions {
  id: bigint;
  customer_id: bigint;
  subscription_plan_id: bigint;
  order_id: bigint;
  start_date: Date;
  end_date: Date;
  status: number;
  created_at: Date | null;
  updated_at: Date | null;
  customers?: customers;
  orders?: orders;
  subscription_plans?: subscription_plans;
  subscription_usages?: subscription_usages[];
}

export interface customers {
  id: bigint;
  first_name: string | null;
  last_name: string | null;
  gender: string | null;
  email: string | null;
  mobile_number: string;
  password: string | null;
  birthdate: Date | null;
  ssn: string | null;
  otp_secret: string | null;
  status: number;
  is_verified: boolean;
  deleted_at: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
  customer_subscriptions?: customer_subscriptions[];
  subscription_usages?: subscription_usages[];
}

export interface failed_jobs {
  id: bigint;
  uuid: string;
  connection: string;
  queue: string;
  payload: string;
  exception: string;
  failed_at: Date;
}

export interface job_batches {
  id: string;
  name: string;
  total_jobs: number;
  pending_jobs: number;
  failed_jobs: number;
  failed_job_ids: string;
  options: string | null;
  cancelled_at: number | null;
  created_at: number;
  finished_at: number | null;
}

export interface jobs {
  id: bigint;
  queue: string;
  payload: string;
  attempts: number;
  reserved_at: number | null;
  available_at: number;
  created_at: number;
}

export interface migrations {
  id: number;
  migration: string;
  batch: number;
}

export interface model_has_permissions {
  permission_id: bigint;
  model_type: string;
  model_id: bigint;
  permissions?: permissions;
}

export interface model_has_roles {
  role_id: bigint;
  model_type: string;
  model_id: bigint;
  roles?: roles;
}

export interface oauth_access_tokens {
  id: string;
  user_id: bigint | null;
  client_id: bigint;
  name: string | null;
  scopes: string | null;
  revoked: boolean;
  created_at: Date | null;
  updated_at: Date | null;
  expires_at: Date | null;
}

export interface oauth_auth_codes {
  id: string;
  user_id: bigint;
  client_id: bigint;
  scopes: string | null;
  revoked: boolean;
  expires_at: Date | null;
}

export interface oauth_clients {
  id: bigint;
  user_id: bigint | null;
  name: string;
  secret: string | null;
  provider: string | null;
  redirect: string;
  personal_access_client: boolean;
  password_client: boolean;
  revoked: boolean;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface oauth_personal_access_clients {
  id: bigint;
  client_id: bigint;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface oauth_refresh_tokens {
  id: string;
  access_token_id: string;
  revoked: boolean;
  expires_at: Date | null;
}

export interface offer_categories {
  id: bigint;
  title: string;
  icon: string | null;
  description: string | null;
  status: number;
  created_at: Date | null;
  updated_at: Date | null;
  offers?: offers[];
  providers?: providers[];
}

export interface offers {
  id: bigint;
  category_id: bigint;
  title: string;
  icon: string | null;
  description: string | null;
  price: Decimal | null;
  created_at: Date | null;
  updated_at: Date | null;
  offer_categories?: offer_categories;
  provider_offers?: provider_offers[];
  subscription_plan_offers?: subscription_plan_offers[];
  subscription_usages?: subscription_usages[];
}

export interface orders {
  id: bigint;
  buyer_type: string;
  buyer_id: bigint;
  purchasable_type: string;
  purchasable_id: bigint;
  amount: Decimal;
  status: number;
  created_at: Date | null;
  updated_at: Date | null;
  tracking_code: string | null;
  customer_subscriptions?: customer_subscriptions | null;
  payments?: payments[];
}

export interface otps {
  id: bigint;
  code: string;
  channel: number;
  reason: string;
  expires_at: Date;
  authenticatable_type: string;
  authenticatable_id: bigint;
  is_used: boolean;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface payments {
  id: bigint;
  order_id: bigint;
  transaction_id: string;
  res_num: string;
  status: number;
  amount: Decimal;
  payment_method: string | null;
  payment_gateway: string | null;
  paid_at: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
  receipt_photo: string | null;
  orders?: orders;
}

export interface permissions {
  id: bigint;
  name: string;
  guard_name: string;
  created_at: Date | null;
  updated_at: Date | null;
  model_has_permissions?: model_has_permissions[];
  role_has_permissions?: role_has_permissions[];
}

export interface personal_access_tokens {
  id: bigint;
  tokenable_type: string;
  tokenable_id: bigint;
  name: string;
  token: string;
  abilities: string | null;
  last_used_at: Date | null;
  expires_at: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface provider_agents {
  id: bigint;
  provider_id: bigint;
  user_id: bigint;
  role: number;
  created_at: Date | null;
  updated_at: Date | null;
  providers?: providers;
  admins?: admins;
  subscription_usages?: subscription_usages[];
}

export interface provider_offers {
  id: bigint;
  provider_id: bigint;
  offer_id: bigint;
  created_at: Date | null;
  updated_at: Date | null;
  offers?: offers;
  providers?: providers;
}

export interface providers {
  id: bigint;
  name: string;
  description: string | null;
  category_id: bigint;
  address: string;
  phone_number: JsonValue;
  main_image: string;
  slider_images: JsonValue;
  latitude: Decimal;
  longitude: Decimal;
  is_verified: boolean;
  status: number;
  created_at: Date | null;
  updated_at: Date | null;
  provider_agents?: provider_agents[];
  provider_menu?: provider_menu | null;
  provider_offers?: provider_offers[];
  offer_categories?: offer_categories;
  subscription_usages?: subscription_usages[];
}

export interface provider_menu {
  id: bigint;
  provider_id: bigint;
  title: string | null;
  description: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  providers?: providers;
  provider_menu_items?: provider_menu_items[];
  provider_menu_categories?: provider_menu_categories[];
}

export interface provider_menu_items {
  id: bigint;
  menu_id: bigint;
  title: string;
  description: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  category_id: bigint;
  price: Decimal;
  provider_menu_categories?: provider_menu_categories;
  provider_menu?: provider_menu;
}

export interface provider_menu_categories {
  id: bigint;
  menu_id: bigint;
  title: string;
  created_at: Date | null;
  updated_at: Date | null;
  provider_menu?: provider_menu;
  provider_menu_items?: provider_menu_items[];
}

export interface role_has_permissions {
  permission_id: bigint;
  role_id: bigint;
  permissions?: permissions;
  roles?: roles;
}

export interface roles {
  id: bigint;
  name: string;
  guard_name: string;
  created_at: Date | null;
  updated_at: Date | null;
  model_has_roles?: model_has_roles[];
  role_has_permissions?: role_has_permissions[];
}

export interface subscription_plan_offers {
  id: bigint;
  subscription_plan_id: bigint;
  offer_id: bigint;
  discount_percentage: number;
  created_at: Date | null;
  updated_at: Date | null;
  offers?: offers;
  subscription_plans?: subscription_plans;
}

export interface subscription_plans {
  id: bigint;
  title: string;
  duration: number;
  price: Decimal;
  status: number;
  description: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  customer_subscriptions?: customer_subscriptions[];
  subscription_plan_offers?: subscription_plan_offers[];
}

export interface subscription_usages {
  id: bigint;
  provider_agent_id: bigint;
  customer_id: bigint;
  customer_subscription_id: bigint;
  provider_id: bigint;
  offer_id: bigint;
  total_amount: string;
  status: string;
  created_at: Date | null;
  updated_at: Date | null;
  customers?: customers;
  customer_subscriptions?: customer_subscriptions;
  offers?: offers;
  provider_agents?: provider_agents;
  providers?: providers;
}

type Decimal = { valueOf(): string };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
